from __future__ import annotations

import time
from typing import Sequence

from demo_v2_1 import realtime_three_view_masked_fused_pcd as _legacy


# Demo 2.2 / 2.1.5 public presets. Keep this module as the import boundary for
# new demos so public wrappers do not depend on the Demo 2.1 entrypoint.
PRESET_DEMO22_ASYNC_FILTER_5FPS = _legacy.PRESET_DEMO22_ASYNC_FILTER_5FPS
PRESET_DEMO22_STAGED_PARALLEL_5FPS = _legacy.PRESET_DEMO22_STAGED_PARALLEL_5FPS
PRESET_DEMO22_SINGLE_OBJECT_BATCHVISION_EDGETAM = _legacy.PRESET_DEMO22_SINGLE_OBJECT_BATCHVISION_EDGETAM
PRESET_DEMO215_ASYNC_FILTER_5FPS = _legacy.PRESET_DEMO215_ASYNC_FILTER_5FPS
PRESET_DEMO215_COMPILED_PARALLEL_EDGETAM_5FPS = _legacy.PRESET_DEMO215_COMPILED_PARALLEL_EDGETAM_5FPS
PRESET_DEMO215_STAGED_PARALLEL_5FPS = _legacy.PRESET_DEMO215_STAGED_PARALLEL_5FPS
PRESET_DEMO215_LIVE_FAST_NATIVE = _legacy.PRESET_DEMO215_LIVE_FAST_NATIVE
PRESET_DEMO215_LIVE_QUALITY_FFS = _legacy.PRESET_DEMO215_LIVE_QUALITY_FFS
PRESET_DEMO215_MASK_ONLY_DEBUG = _legacy.PRESET_DEMO215_MASK_ONLY_DEBUG

TRACK_MODE_OBJECT_ONLY = _legacy.TRACK_MODE_OBJECT_ONLY
TRACK_MODE_CONTROLLER_OBJECT = _legacy.TRACK_MODE_CONTROLLER_OBJECT

EDGETAM_BACKEND_HF_SEQ_SESSION = _legacy.EDGETAM_BACKEND_HF_SEQ_SESSION
EDGETAM_BACKEND_HF_BATCH_VISION_SEQ_SESSION = _legacy.EDGETAM_BACKEND_HF_BATCH_VISION_SEQ_SESSION
EDGETAM_BACKEND_HF_BATCHED_MULTISESSION = _legacy.EDGETAM_BACKEND_HF_BATCHED_MULTISESSION
EDGETAM_BACKENDS = _legacy.EDGETAM_BACKENDS

DEPTH_SOURCE_FFS = _legacy.DEPTH_SOURCE_FFS
DEPTH_SOURCE_FFS_REMOTE = _legacy.DEPTH_SOURCE_FFS_REMOTE
DEPTH_SOURCE_REALSENSE = _legacy.DEPTH_SOURCE_REALSENSE
DEPTH_SOURCE_NONE = _legacy.DEPTH_SOURCE_NONE
DEPTH_SOURCES = _legacy.DEPTH_SOURCES

GPU_PIPELINE_MODE_SEPARATE_WORKERS = _legacy.GPU_PIPELINE_MODE_SEPARATE_WORKERS
GPU_PIPELINE_MODE_SINGLE_OWNER = _legacy.GPU_PIPELINE_MODE_SINGLE_OWNER
GPU_PIPELINE_MODE_STAGED = _legacy.GPU_PIPELINE_MODE_STAGED
SINGLE_OWNER_ORDER_FFS_THEN_EDGETAM = _legacy.SINGLE_OWNER_ORDER_FFS_THEN_EDGETAM
STAGED_ORDER_FFS_THEN_PARALLEL_EDGETAM = _legacy.STAGED_ORDER_FFS_THEN_PARALLEL_EDGETAM

EDGETAM_MODEL_TOPOLOGY_REPLICATED = _legacy.EDGETAM_MODEL_TOPOLOGY_REPLICATED
EDGETAM_MODEL_TOPOLOGY_SHARED = _legacy.EDGETAM_MODEL_TOPOLOGY_SHARED
EDGETAM_STREAM_MODE_PER_CAMERA = _legacy.EDGETAM_STREAM_MODE_PER_CAMERA

PIN_MEMORY_MODE_ALL = _legacy.PIN_MEMORY_MODE_ALL
H2D_STREAM_MODE_DEDICATED = _legacy.H2D_STREAM_MODE_DEDICATED
POSTPROCESS_NONE = _legacy.POSTPROCESS_NONE

DEFAULT_COMPILE_MODE = _legacy.DEFAULT_COMPILE_MODE
COMPILE_MODE_NONE = _legacy.COMPILE_MODE_NONE
COMPILE_MODE_VISION_REDUCE_OVERHEAD = _legacy.COMPILE_MODE_VISION_REDUCE_OVERHEAD
COMPILE_MODE_VISION_MAX_AUTOTUNE_NO_CUDAGRAPHS = _legacy.COMPILE_MODE_VISION_MAX_AUTOTUNE_NO_CUDAGRAPHS
COMPILE_MODE_COMPONENTS_REDUCE_OVERHEAD = _legacy.COMPILE_MODE_COMPONENTS_REDUCE_OVERHEAD
COMPILE_MODE_COMPONENTS_MAX_AUTOTUNE_NO_CUDAGRAPHS = _legacy.COMPILE_MODE_COMPONENTS_MAX_AUTOTUNE_NO_CUDAGRAPHS
COMPILE_MODE_REDUCE_OVERHEAD = _legacy.COMPILE_MODE_REDUCE_OVERHEAD
COMPILE_MODE_MAX_AUTOTUNE_NO_CUDAGRAPHS = _legacy.COMPILE_MODE_MAX_AUTOTUNE_NO_CUDAGRAPHS
MASK_POSTPROCESS_HF = _legacy.MASK_POSTPROCESS_HF
MASK_POSTPROCESS_CUDA_INLINE = _legacy.MASK_POSTPROCESS_CUDA_INLINE
MASK_POSTPROCESS_MODES = _legacy.MASK_POSTPROCESS_MODES
EDGETAM_PRECISION_MODES = _legacy.EDGETAM_PRECISION_MODES
EDGETAM_PRECISION_MODE_MEMORY_PATH_FP32 = _legacy.EDGETAM_PRECISION_MODE_MEMORY_PATH_FP32
EDGETAM_COMPONENT_RUNTIME_TORCH = _legacy.EDGETAM_COMPONENT_RUNTIME_TORCH
EDGETAM_COMPONENT_RUNTIME_TRT = _legacy.EDGETAM_COMPONENT_RUNTIME_TRT
EDGETAM_COMPONENT_RUNTIMES = _legacy.EDGETAM_COMPONENT_RUNTIMES
EDGETAM_TRT_SCOPE_MEMORY_PATH_ALL = _legacy.EDGETAM_TRT_SCOPE_MEMORY_PATH_ALL
EDGETAM_TRT_SCOPES = _legacy.EDGETAM_TRT_SCOPES
DEFAULT_BATCHTAM_TRT_ENGINE_DIR = _legacy.DEFAULT_BATCHTAM_TRT_ENGINE_DIR
DEFAULT_BATCHTAM_TRT_REPORT = _legacy.DEFAULT_BATCHTAM_TRT_REPORT
DEFAULT_DEMO22_DEPTH_MIN_M = _legacy.DEFAULT_DEMO22_DEPTH_MIN_M
DEFAULT_FFS_TRT_TWO_STAGE_MODEL_DIR = _legacy.DEFAULT_FFS_TRT_TWO_STAGE_MODEL_DIR
DEFAULT_FFS_TRT_BATCH3_TWO_STAGE_MODEL_DIR = _legacy.DEFAULT_FFS_TRT_BATCH3_TWO_STAGE_MODEL_DIR
FFS_TRT_BATCH_SIZES = _legacy.FFS_TRT_BATCH_SIZES
GPU_SAMPLING_BACKENDS = _legacy.GPU_SAMPLING_BACKENDS
COMPILE_MODE_VISION_DEFAULT = _legacy.COMPILE_MODE_VISION_DEFAULT

CameraFramePacket = _legacy.CameraFramePacket
CameraIntrinsics = _legacy.CameraIntrinsics
CaptureGroup = _legacy.CaptureGroup
FusedLayerCloud = _legacy.FusedLayerCloud
RawFusedPcdPacket = _legacy.RawFusedPcdPacket

Demo22Runtime = _legacy.Demo21Runtime

elapsed_ms = _legacy._elapsed_ms
explicit_cli_options = _legacy._explicit_cli_options
summarize_gpu_samples = _legacy.summarize_gpu_samples
load_full_batched_edgetam_report = _legacy.load_full_batched_edgetam_report
load_batchtam_trt_report = _legacy.load_batchtam_trt_report
validate_full_batched_edgetam_report = _legacy.validate_full_batched_edgetam_report
validate_batchtam_trt_report = _legacy.validate_batchtam_trt_report
validate_batchtam_trt_artifacts = _legacy.validate_batchtam_trt_artifacts
final_fps_from_demo22_profile = _legacy.final_fps_from_demo22_profile
external_git_commit = _legacy.external_git_commit
attach_full_batched_report_validation = _legacy.attach_full_batched_report_validation
attach_batchtam_trt_report_validation = _legacy.attach_batchtam_trt_report_validation


def parse_camera_ids(value: str) -> tuple[int, ...]:
    return _legacy.parse_camera_ids(value)


def build_arg_parser():
    return _legacy.build_arg_parser()


def apply_preset_defaults(args, *, explicit_options: set[str] | None = None):
    return _legacy.apply_preset_defaults(args, explicit_options=explicit_options)


def build_contract(args) -> dict:
    return _legacy.build_contract(args)


def main(argv: Sequence[str] | None = None) -> int:
    return _legacy.main(argv)


__all__ = [
    "CameraFramePacket",
    "CameraIntrinsics",
    "CaptureGroup",
    "COMPILE_MODE_VISION_DEFAULT",
    "COMPILE_MODE_VISION_REDUCE_OVERHEAD",
    "COMPILE_MODE_VISION_MAX_AUTOTUNE_NO_CUDAGRAPHS",
    "COMPILE_MODE_COMPONENTS_REDUCE_OVERHEAD",
    "COMPILE_MODE_COMPONENTS_MAX_AUTOTUNE_NO_CUDAGRAPHS",
    "COMPILE_MODE_REDUCE_OVERHEAD",
    "COMPILE_MODE_MAX_AUTOTUNE_NO_CUDAGRAPHS",
    "COMPILE_MODE_NONE",
    "DEFAULT_COMPILE_MODE",
    "DEFAULT_DEMO22_DEPTH_MIN_M",
    "DEFAULT_FFS_TRT_BATCH3_TWO_STAGE_MODEL_DIR",
    "DEFAULT_FFS_TRT_TWO_STAGE_MODEL_DIR",
    "DEPTH_SOURCE_FFS",
    "DEPTH_SOURCE_FFS_REMOTE",
    "DEPTH_SOURCE_NONE",
    "DEPTH_SOURCE_REALSENSE",
    "DEPTH_SOURCES",
    "Demo22Runtime",
    "EDGETAM_MODEL_TOPOLOGY_REPLICATED",
    "EDGETAM_MODEL_TOPOLOGY_SHARED",
    "EDGETAM_STREAM_MODE_PER_CAMERA",
    "EDGETAM_PRECISION_MODES",
    "EDGETAM_PRECISION_MODE_MEMORY_PATH_FP32",
    "EDGETAM_COMPONENT_RUNTIME_TORCH",
    "EDGETAM_COMPONENT_RUNTIME_TRT",
    "EDGETAM_COMPONENT_RUNTIMES",
    "EDGETAM_TRT_SCOPE_MEMORY_PATH_ALL",
    "EDGETAM_TRT_SCOPES",
    "EDGETAM_BACKEND_HF_BATCHED_MULTISESSION",
    "EDGETAM_BACKEND_HF_BATCH_VISION_SEQ_SESSION",
    "EDGETAM_BACKEND_HF_SEQ_SESSION",
    "EDGETAM_BACKENDS",
    "FFS_TRT_BATCH_SIZES",
    "FusedLayerCloud",
    "GPU_PIPELINE_MODE_SEPARATE_WORKERS",
    "GPU_PIPELINE_MODE_SINGLE_OWNER",
    "GPU_PIPELINE_MODE_STAGED",
    "GPU_SAMPLING_BACKENDS",
    "H2D_STREAM_MODE_DEDICATED",
    "MASK_POSTPROCESS_CUDA_INLINE",
    "MASK_POSTPROCESS_HF",
    "MASK_POSTPROCESS_MODES",
    "DEFAULT_BATCHTAM_TRT_ENGINE_DIR",
    "DEFAULT_BATCHTAM_TRT_REPORT",
    "PIN_MEMORY_MODE_ALL",
    "POSTPROCESS_NONE",
    "PRESET_DEMO215_ASYNC_FILTER_5FPS",
    "PRESET_DEMO215_COMPILED_PARALLEL_EDGETAM_5FPS",
    "PRESET_DEMO215_LIVE_FAST_NATIVE",
    "PRESET_DEMO215_LIVE_QUALITY_FFS",
    "PRESET_DEMO215_MASK_ONLY_DEBUG",
    "PRESET_DEMO215_STAGED_PARALLEL_5FPS",
    "PRESET_DEMO22_ASYNC_FILTER_5FPS",
    "PRESET_DEMO22_SINGLE_OBJECT_BATCHVISION_EDGETAM",
    "PRESET_DEMO22_STAGED_PARALLEL_5FPS",
    "RawFusedPcdPacket",
    "SINGLE_OWNER_ORDER_FFS_THEN_EDGETAM",
    "STAGED_ORDER_FFS_THEN_PARALLEL_EDGETAM",
    "TRACK_MODE_CONTROLLER_OBJECT",
    "TRACK_MODE_OBJECT_ONLY",
    "apply_preset_defaults",
    "attach_full_batched_report_validation",
    "attach_batchtam_trt_report_validation",
    "build_arg_parser",
    "build_contract",
    "elapsed_ms",
    "explicit_cli_options",
    "external_git_commit",
    "final_fps_from_demo22_profile",
    "load_full_batched_edgetam_report",
    "load_batchtam_trt_report",
    "main",
    "parse_camera_ids",
    "summarize_gpu_samples",
    "validate_full_batched_edgetam_report",
    "validate_batchtam_trt_report",
    "validate_batchtam_trt_artifacts",
    "time",
]
