"""Phystwin_shen CLI-contract compatibility (v7-side, both repos read-only).

Broken since 2026-07-10 and never noticed until the first full GUI run
(2026-08-07): demo_v6_2's launcher emits per-stage window overrides
(``--stage1_batch_size`` etc., from config phystwin_shen.stage1/train
sections) but Phystwin_shen's current ``run_online_full_pipeline.py``
dropped those CLI flags that same day — argparse exits with code 2 and the
whole downstream dies (`unrecognized arguments`, seen in every log since
outputs/phystwin_shen/online_full_pipeline.log of Jul 12).

The script still honors per-stage windows FROM ITS YAML CONFIG
(``stage_options``: yaml stage section overrides yaml common), so the
values have a fully-supported home: this wrapper moves the rejected flags
into a generated copy of the pipeline yaml and swaps ``--config`` to it.
The demo config's exact per-stage values (stage1 2/10/10, train 5/30/30)
are preserved — no semantic drift — and if the two repos ever re-sync
their CLI contract the rewrite naturally no-ops (no rejected flags found).
"""

from __future__ import annotations

from pathlib import Path

_WINDOW_SECTIONS = ("stage1", "stage2", "train")
_WINDOW_KEYS = ("batch_size", "segment_len", "segment_stride")
_REJECTED_FLAGS = {
    f"--{section}_{key}": (section, key)
    for section in _WINDOW_SECTIONS
    for key in _WINDOW_KEYS
}


def rewrite_window_flags(command: list[str]) -> list[str]:
    """Move per-stage window flags into a generated ``--config`` yaml."""
    import yaml

    moved: dict[tuple[str, str], int] = {}
    kept: list[str] = []
    index = 0
    while index < len(command):
        token = command[index]
        if token in _REJECTED_FLAGS and index + 1 < len(command):
            moved[_REJECTED_FLAGS[token]] = int(command[index + 1])
            index += 2
            continue
        kept.append(token)
        index += 1
    if not moved:
        return command  # contract re-synced upstream; nothing to do

    config_index = kept.index("--config") + 1
    online_dir_index = kept.index("--online_dir") + 1
    source_config = Path(kept[config_index])
    config = yaml.safe_load(source_config.read_text()) or {}
    for (section, key), value in moved.items():
        section_map = config.setdefault(section, {})
        if not isinstance(section_map, dict):
            section_map = {}
            config[section] = section_map
        section_map[key] = value

    generated_dir = Path(kept[online_dir_index]).parent / "phystwin_shen"
    generated_dir.mkdir(parents=True, exist_ok=True)
    generated = generated_dir / "pipeline_config_windows.yaml"
    generated.write_text(
        "# Generated by demo_v7 phystwin_compat: per-stage window overrides\n"
        f"# merged into {source_config} (its CLI no longer accepts them).\n"
        + yaml.safe_dump(config, sort_keys=False)
    )
    kept[config_index] = str(generated)
    print(
        "[phystwin-compat] moved "
        + ", ".join(f"{s}.{k}={v}" for (s, k), v in sorted(moved.items()))
        + f" into {generated} (per-stage window CLI flags were dropped "
        "upstream 2026-07-10)",
        flush=True,
    )
    return kept


def patch_phystwin_stage_window_compat() -> None:
    """Rebind the v6.2 command builder with the window-flag rewrite."""
    from demo_v6_2 import phystwin_shen_launch as launch_module

    if getattr(
        launch_module.build_full_pipeline_command, "_v7_window_compat", False
    ):
        return
    stock_builder = launch_module.build_full_pipeline_command

    def build_with_window_compat(settings, *, python_prefix):
        command = stock_builder(settings, python_prefix=python_prefix)
        try:
            return rewrite_window_flags(list(command))
        except Exception as exc:
            # Fail-soft: a broken rewrite must not block the launch attempt
            # (the stock command's failure mode is at least well understood).
            print(
                f"[phystwin-compat] window-flag rewrite skipped "
                f"({type(exc).__name__}: {exc}); passing the stock command",
                flush=True,
            )
            return command

    build_with_window_compat._v7_window_compat = True
    launch_module.build_full_pipeline_command = build_with_window_compat
