"""Legacy compatibility wrapper for :mod:`demo_v5_1.data_process_chunk_writer`."""
from __future__ import annotations

from demo_v5_1.data_process_chunk_writer import *  # noqa: F401,F403
from demo_v5_1.data_process_chunk_writer import (
    CONTROLLER_CANDIDATE_POINT_KEYS,
    CONTROLLER_CANDIDATE_TIME_KEYS,
    CONTROLLER_TRACK_STATIC_KEYS,
    CONTROLLER_TRACK_TIME_KEYS,
    DATA_PROCESS_FINAL_DATA_KEYS,
    DATA_PROCESS_QUERY_SCHEMA_KEYS,
    DATA_PROCESS_QUERY_SCHEMA_VERSION,
    DATA_PROCESS_SAM3D_METRICS,
    DATA_PROCESS_SAM3D_REALTIME_CONTRACT_VERSION,
    DATA_PROCESS_TRACK_PROCESS_KEYS,
    DATA_PROCESS_TRACK_PROCESS_TRACE_KEYS,
    DataProcessChunk,
    build_query_schema_payload,
    validate_data_process_case,
    write_data_process_chunk_case,
)


FuturePhysTwinChunk = DataProcessChunk
FUTUREPHYSTWIN_FINAL_DATA_KEYS = DATA_PROCESS_FINAL_DATA_KEYS
FUTUREPHYSTWIN_TOPOLOGY_KEYS = DATA_PROCESS_QUERY_SCHEMA_KEYS
FUTUREPHYSTWIN_TOPOLOGY_VERSION = DATA_PROCESS_QUERY_SCHEMA_VERSION
FUTUREPHYSTWIN_TRACK_PROCESS_KEYS = DATA_PROCESS_TRACK_PROCESS_KEYS
FUTUREPHYSTWIN_TRACK_PROCESS_TRACE_KEYS = DATA_PROCESS_TRACK_PROCESS_TRACE_KEYS
FUTUREPHYSTWIN_REALTIME_CONTRACT_VERSION = DATA_PROCESS_SAM3D_REALTIME_CONTRACT_VERSION
PHYSTWIN_STRICT_METRICS = DATA_PROCESS_SAM3D_METRICS
CONTROLLER_ANCHOR_TIME_KEYS = CONTROLLER_TRACK_TIME_KEYS
CONTROLLER_ANCHOR_STATIC_KEYS = CONTROLLER_TRACK_STATIC_KEYS
CONTROLLER_QUALITY_STATUSES = ("normal", "degraded", "invalid")

build_topology_payload = build_query_schema_payload
validate_futurephystwin_case = validate_data_process_case
write_futurephystwin_chunk_case = write_data_process_chunk_case


__all__ = [
    "CONTROLLER_ANCHOR_STATIC_KEYS",
    "CONTROLLER_ANCHOR_TIME_KEYS",
    "CONTROLLER_CANDIDATE_POINT_KEYS",
    "CONTROLLER_CANDIDATE_TIME_KEYS",
    "CONTROLLER_QUALITY_STATUSES",
    "FUTUREPHYSTWIN_FINAL_DATA_KEYS",
    "FUTUREPHYSTWIN_REALTIME_CONTRACT_VERSION",
    "FUTUREPHYSTWIN_TOPOLOGY_KEYS",
    "FUTUREPHYSTWIN_TOPOLOGY_VERSION",
    "FUTUREPHYSTWIN_TRACK_PROCESS_KEYS",
    "FUTUREPHYSTWIN_TRACK_PROCESS_TRACE_KEYS",
    "FuturePhysTwinChunk",
    "PHYSTWIN_STRICT_METRICS",
    "build_topology_payload",
    "validate_futurephystwin_case",
    "write_futurephystwin_chunk_case",
]
