name: phystwin-max
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ffmpeg
  - libstdcxx-ng
  - libgcc-ng
  - pkg-config
  - cmake
  - ninja
  - git
  - git-lfs
  - curl
  - wget
  - libgl
  - libglib
