from __future__ import annotations

from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[2]


def run(cmd: list[str]) -> None:
    print(f"[check] {' '.join(cmd)}")
    subprocess.run(cmd, check=True, cwd=ROOT)


def main() -> int:
    python = sys.executable
    run([python, "cameras_viewer.py", "--help"])
    run([python, "cameras_viewer_FFS.py", "--help"])
    run([python, "cameras_calibrate.py", "--help"])
    run([python, "record_data.py", "--help"])
    run([python, "data_process/record_data_align.py", "--help"])
    run([python, "scripts/harness/verify_ffs_demo.py", "--help"])
    run([python, "scripts/harness/probe_d455_ir_pair.py", "--help"])
    run([python, "scripts/harness/probe_d455_stream_capability.py", "--help"])
    run([python, "scripts/harness/render_d455_stream_probe_report.py", "--help"])
    run([python, "scripts/harness/generate_sam31_masks.py", "--help"])
    run([python, "scripts/harness/visual_compare_depth_panels.py", "--help"])
    run([python, "scripts/harness/diagnose_floating_point_sources.py", "--help"])
    run([python, "scripts/harness/benchmark_ffs_configs.py", "--help"])
    run([python, "scripts/harness/visual_compare_reprojection.py", "--help"])
    run([python, "scripts/harness/visual_compare_depth_video.py", "--help"])
    run([python, "scripts/harness/visual_compare_depth_triplet_ply.py", "--help"])
    run([python, "scripts/harness/visual_compare_depth_triplet_video.py", "--help"])
    run([python, "scripts/harness/visual_compare_rerun.py", "--help"])
    run([python, "scripts/harness/visual_compare_turntable.py", "--help"])
    run([python, "scripts/harness/visual_compare_stereo_order_pcd.py", "--help"])
    run([python, "scripts/harness/visual_make_professor_triptych.py", "--help"])
    run([python, "scripts/harness/visual_make_match_board.py", "--help"])
    run([python, "scripts/harness/audit_ffs_left_right.py", "--help"])
    run([python, "scripts/harness/compare_face_smoothness.py", "--help"])
    run([python, "scripts/harness/check_visual_architecture.py"])
    run([python, "scripts/harness/run_ffs_on_saved_pair.py", "--help"])
    run([python, "scripts/harness/reproject_ffs_to_color.py", "--help"])
    run([python, "scripts/harness/cleanup_different_types_cases.py", "--help"])
    run([python, "-m", "scripts.harness.check_scope"])
    run([python, "-m", "unittest", "-v", "tests.test_agents_scope_contract_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_cameras_viewer_fps_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_cameras_viewer_ffs_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_record_data_align_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_ffs_intrinsic_file_format"])
    run([python, "-m", "unittest", "-v", "tests.test_ffs_reprojection_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_depth_quantization_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_depth_colormap_consistency_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_depth_panel_layout_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_depth_panel_roi_overlay_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_depth_panel_preset_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_floating_point_diagnostics_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_ffs_benchmarking_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_sam31_mask_helper_smoke"])
    run([python, "-m", "pytest", "tests/test_d455_probe_matrix_builder.py", "tests/test_d455_probe_result_schema.py"])
    run([python, "-m", "unittest", "-v", "tests.test_recording_metadata_schema_v2"])
    run([python, "-m", "unittest", "-v", "tests.test_camera_system_partial_stall_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_single_realsense_recovery_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_record_preflight_policy_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_record_data_preflight_message_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_depth_backend_contract_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_ffs_remove_invisible_mask_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_ffs_native_like_depth_postprocess_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_record_data_align_ffs_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_record_data_align_both_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_calibrate_loader_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_calibration_contract_hardening"])
    run([python, "-m", "unittest", "-v", "tests.test_camera_pose_view_config_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_camera_frusta_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_object_centered_orbit_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_observed_hemisphere_orbit_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_auto_object_bbox_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_dual_render_output_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_dual_triple_output_planning_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_camera_overview_inset_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_support_render_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_full_360_unsupported_annotation_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_table_crop_roi_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_table_focus_center_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_manual_image_roi_filter_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_auto_object_refinement_from_projected_bbox_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_graph_union_preserves_protrusion_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_pixel_mask_expands_world_roi_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_compare_debug_metrics_refinement_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_object_compare_contract_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_source_id_propagation_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_source_attribution_overlay_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_source_split_render_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_mismatch_residual_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_source_legend_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_visual_import_graph_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_visual_types_contract_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_selection_contracts_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_artifact_writer_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_layout_builder_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_merge_diagnostics_workflow_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_turntable_workflow_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_turntable_frame_contract_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_object_union_bbox_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_object_first_sampling_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_object_debug_artifacts_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_pointcloud_fusion_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_aligned_metadata_loader_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_io_case_ffs_native_like_loader_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_grid_2x3_label_layout_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_projection_mode_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_fallback_splat_render_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_grouped_aligned_case_resolution_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_single_frame_case_selection_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_turntable_view_generation_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_turntable_board_layout_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_keyframe_sheet_generation_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_professor_triptych_angle_selection_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_professor_triptych_output_contract_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_match_board_angle_selection_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_match_board_output_contract_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_match_board_layout_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_match_board_legend_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_left_right_audit_stats_generation"])
    run([python, "-m", "unittest", "-v", "tests.test_raw_clipped_disparity_audit_path"])
    run([python, "-m", "unittest", "-v", "tests.test_face_patch_json_parsing"])
    run([python, "-m", "unittest", "-v", "tests.test_plane_fit_metric_computation"])
    run([python, "-m", "unittest", "-v", "tests.test_face_quality_board_layout"])
    run([python, "-m", "unittest", "-v", "tests.test_semantic_world_inference_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_stereo_order_registration_layout_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_stereo_order_registration_source_color_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_stereo_order_registration_workflow_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_visual_compare_depth_panels_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_diagnose_floating_point_sources_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_visual_compare_reprojection_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_fused_cloud_render_config_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_visual_compare_depth_video_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_visual_compare_depth_video_grid_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_triplet_ply_compare_workflow_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_triplet_video_compare_workflow_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_rerun_compare_workflow_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_visual_compare_turntable_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_visual_make_professor_triptych_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_visual_make_match_board_smoke"])
    run([python, "-m", "unittest", "-v", "tests.test_cleanup_different_types_cases_smoke"])
    print("[check] all deterministic checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
