#!/usr/bin/env bash
set -euo pipefail

# WSLg/Open3D GUI repair shim for Demo 2.1.

unset VK_ICD_FILENAMES
unset __GLX_VENDOR_LIBRARY_NAME
unset __EGL_VENDOR_LIBRARY_FILENAMES
unset LD_PRELOAD

export WAYLAND_DISPLAY=""
export EGL_PLATFORM="${EGL_PLATFORM:-x11}"
export GALLIUM_DRIVER="${GALLIUM_DRIVER:-d3d12}"
export MESA_LOADER_DRIVER_OVERRIDE="${MESA_LOADER_DRIVER_OVERRIDE:-d3d12}"
export LIBGL_ALWAYS_SOFTWARE="${LIBGL_ALWAYS_SOFTWARE:-0}"
export QQTT_WSLG_OPEN3D_FAST_EXIT="${QQTT_WSLG_OPEN3D_FAST_EXIT:-1}"
export MESA_D3D12_DEFAULT_ADAPTER_NAME="${MESA_D3D12_DEFAULT_ADAPTER_NAME:-NVIDIA}"

exec "$@"
